### ISSUE TITLE
How to run pytest with custom DJANGO_SETTINGS_MODULE in pretix development

### ISSUE THREAD

**Issue by MaicoTimmerman** [pretix/pretix-plugin-cookiecutter#11]
I updated our authentication plugin for Pretix with the 4.7 changes and wanted to create tests. Given that our plugin is based on the cookiecutter, this would seem the best place to open this issue.

To test our custom authentication backend, we need to adjust the settings module to one included in the plugin. Given that we have a custom settings file `tests/settings.py`:
```py
from pretix.testutils.settings import *  # NOQA
PRETIX_AUTH_BACKENDS = ["pretix_superplugin.SuperOAuthBackend"]
```
And I adopt the following change:
```diff
diff --git a/setup.cfg b/setup.cfg
index 30aed19..9b82383 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -17,7 +17,7 @@ line_length = 88
 known_first_party = pretix_superplugin
 
 [tool:pytest]
-DJANGO_SETTINGS_MODULE = pretix.testutils.settings
+DJANGO_SETTINGS_MODULE = tests.settings
 
 [coverage:run]
 source = pretix_superplugin
```
Given I've also installed pretix and it's development setup: `pip install pretix[dev]`. Without, `pytest-django`, the included tests work, however for obvious reasons we'd want to use things like `@pytest.mark.django_db`. Running `pytest` with `[dev]`-dependencies installed, we run into the following error:
```pytb
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/pytest_django/plugin.py", line 183, in _handle_import_error
    raise ImportError(msg)
ImportError: No module named 'tests.settings'

pytest-django could not find a Django project (no manage.py file could be found). You must explicitly add your Django project to the Python path to have it picked up.
```
<details>

<summary>Full traceback</summary>

```pytb
Traceback (most recent call last):
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/pytest_django/plugin.py", line 179, in _handle_import_error
    yield
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/pytest_django/plugin.py", line 351, in pytest_load_initial_conftests
    dj_settings.DATABASES
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tests.settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pretix-superplugin/venv/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1191, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/pytest_django/plugin.py", line 351, in pytest_load_initial_conftests
    dj_settings.DATABASES
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/tmp/pretix-superplugin/venv/lib/python3.8/site-packages/pytest_django/plugin.py", line 183, in _handle_import_error
    raise ImportError(msg)
ImportError: No module named 'tests.settings'

pytest-django could not find a Django project (no manage.py file could be found). You must explicitly add your Django project to the Python path to have it picked up.
```

</details>

I've attempted to debug this but am stuck on this. I've looked through the tests in various public plugins, but could not locate any using custom settings. Any clue to how I might go about this scenario? Perhaps you're open to sharing how plugins with required custom settings are set-up, that are developed non-publicly.

**Comment by MaicoTimmerman** [comment]
I've narrowed this issue down to be a problem with the distributions of `mt-940`. For reference: https://github.com/WoLpH/mt940/issues/78#issuecomment-1057265300

As a work-around I've now renamed my local testing directory from `tests` to `pytests` and adjusted `setup.cfg` with the following patch;
```patch
diff --git a/setup.cfg b/setup.cfg
index 5692383..a093563 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -14,7 +14,7 @@ not_skip = __init__.py
 skip = setup.py
 
 [tool:pytest]
-DJANGO_SETTINGS_MODULE = pretix.testutils.settings
+DJANGO_SETTINGS_MODULE = pytests.settings
 filterwarnings =
     ignore::django.utils.deprecation.RemovedInDjango40Warning
     ignore::DeprecationWarning:pretix
```
